# Generated by Django 5.2 on 2025-09-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_payment_method_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('success', 'Success'), ('in_progress', 'In Progress')], default='in_progress', max_length=20),
        ),
    ]
